
---

#######
# Dir #
#######

manala_deploy_dir: /home/tom32i/lab/binary-brain

############
# Releases #
############

manala_deploy_releases: 3

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    "{{ lookup('pipe','git config --get remote.origin.url') }}"
manala_deploy_strategy_git_version: "{{ lookup('pipe','git rev-parse --abbrev-ref HEAD') }}"

##########
# Copied #
##########

manala_deploy_copied:
  - live/node_modules
  - node_modules

##########
# Shared #
##########

#manala_deploy_shared_files: []
#manala_deploy_shared_dirs: []

############
# Writable #
############

#manala_deploy_writable_dirs_default:
#  mode: ug=rwx,o=rx
#manala_deploy_writable_dirs:
#  - var/cache
#  - var/logs
#  - var/sessions
